### ISSUE TITLE
What is the format for bounties?

### ISSUE THREAD

**Issue by dandv** [bevacqua/awesome-badges#1]
https://img.shields.io/bountysource/team/awesome-badges/activity.svg - how do the org, repo and issue factor in here?

I posted a $100 bounty for https://github.com/linuxmint/Cinnamon/issues/3883 at https://www.bountysource.com/issues/8351500-cinnamon-should-support-hotkeys-window-shortcuts-for-selecting-existing-windows, and I'm surprised that Bountysource doesn't make it easy to add a badge.

**Comment by bevacqua** [comment]
I have no clue. Ask them maybe! 💃

**Comment by dandv** [comment]
Well, I saw "bounties" in the README. Not clear what the purpose of this repo is - badges you'd like to keep handy? Sorry to intrude then :)

Anyway, the Markdown is

```
[![Bountysource][1]][2]
[1]:http://bountysource.com/badge/issue?issue_id=8351500
[2]:https://www.bountysource.com/issues/8351500-cinnamon-should-support-hotkeys-window-shortcuts-for-selecting-existing-windows
```

No need for shields.io.

**Comment by bevacqua** [comment]
There's absolutely no purpose for this repo, just a list of badges you could use. Sorry for the confusion!
